### ISSUE TITLE
Usando client_secret y client_id (para checkout basico) da error de "invalid access token" despues de 24 hs. 

### ISSUE THREAD

**Issue by kingmatusevich** [mercadopago/dx-nodejs#103]

**Comment by kingmatusevich** [comment]
Cerrar el ticket no elimina el problema.

**Comment by joelibaceta** [comment]
Este es un canal para revisar bugs o errores en la implementación del SDK, el problema que reportas se debe a un comportamiento normal del SDK, los live token (generados a partir de un client_id y client_secret) expiran en 6 horas, debes solicitar nuevos. 

**Canal de soporte oficial para desarrolladores:** [https://www.mercadopago.com.ar/developers/es/support](https://www.mercadopago.com.ar/developers/es/support)
