### ISSUE TITLE
Using the Basic Checkout credentials, the server throws token error after a certain amount of hours of the node instance running

### ISSUE THREAD

**Issue by kingmatusevich** [mercadopago/dx-nodejs#105]
**Describe the bug**
When you configure the nodejs library to use the Basic Checkout credentials (because you are implementing a Basic Checkout, that doesn't require homologation), and keep the node instance running for a certain amount of time (I've tested it with 24hrs), and then try to for example create a payment preference, the MP API replies with an invalid token error.

**To Reproduce**
1. Write a simple node script to configure the SDK's credentials with the Basic Checkout style (CLIENT_ID and CLIENT_SECRET), and ask it to create a preference now, and create a preference in 24hs
2. Run the node script (and keep it running)
3. The first immediate preference creation succeeds.
4. Wait 24 hs
5. The delayed preference creation will fail with an Invalid Token error.

**Expected behavior**
The delayed preference is created, or there's a method in the node library to trigger a refresh of whatever is expiring. Either that or we get a blessing to use the production Personalised Checkout token in our basic checkout process without homologation.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX/CentOS/Any Linux
 - Browser [e.g. chrome, safari] Any

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Irrelevant
 - OS: [e.g. iOS8.1] Irrelevant
 - Browser [e.g. stock browser, safari] Irrelevant
 - Version [e.g. 22] Irrelevant

**Additional context**
If you try the same thing with the Production Personalised Checkout credentials, you won't have this problem. However, per the Mercadopago docs, even though you can get the production Personalised Checkout credentials without going through the homologation process [here](https://www.mercadopago.com/mla/account/credentials), It clearly says that you should first go through the homologation process to use them. If I'm only doing a basic checkout, that shouldn't be necessary.

**Comment by kingmatusevich** [comment]
Because the library is implemented as a singleton, it's also not possible once expired to destroy and construct a new lib object to work around the problem. The only way to escape it is to use the Personalised Checkout token (which we're explicitly told not to use), or to reset the server process every so many hours, something that brings it's own bag of issues.

**Comment by arielfr** [comment]
Hi @kingmatusevich @esgama . The refresh_token is deprecated, can't refresh token anymore. The solution is to always generate the token when a request is done. There was a bug, and it was saving the token instead of regenerating it any time if you use client_id and client_secret.

I'm sorry to hear that this cause you trouble. A new version of the SDK with the fix was generated on NPM. Please update to the version `npm@1.0.17`. Thanks for your support

Cheers!
