### ISSUE TITLE
Mercado pago documentation instructs developers to use an outdated version of the SDK

### ISSUE THREAD

**Issue by LukasMeine** [mercadopago/dx-nodejs#108]
**Describe the bug**
If you follow the documentation at the mercado pago website, you get a warning about a SDK deprecation.

**To Reproduce**

1- Literally follow exactly what the documentation says at: https://www.mercadopago.com.br/developers/pt/plugins_sdks/sdks/official/nodejs/

2- see the following message: "'This way of initializing the SDK is deprecated. Please change following the documentation"

**Expected behavior**
Documentation on mercadopago should be updated according with the documentation presented here in this repository

**Screenshots**

![image](https://user-images.githubusercontent.com/20716798/43160813-9fff8208-8f5c-11e8-97cd-889c74505466.png)
![image](https://user-images.githubusercontent.com/20716798/43160924-e8b701a6-8f5c-11e8-9df7-9695e6d4b312.png)
![Documentation misleads the user into using an outdated SDK](https://user-images.githubusercontent.com/20716798/43162718-537bc59e-8f62-11e8-8daa-28aba246fb7d.png)

**Comment by LukasMeine** [comment]
Looks like you guys forgot to remove the deprecation message in the latest SDK. You recommend using this one, but the message persists in https://github.com/mercadopago/dx-nodejs/blob/master/lib/mercadopago.js at line 26

![image](https://user-images.githubusercontent.com/20716798/43161780-6f831164-8f5f-11e8-8ef2-6061e318247f.png)

**Comment by paulogdm** [comment]
Indeed, hope you get some attention because the documentation sure needs some love.

**Comment by arielfr** [comment]
@LukasMeine you're right, the documentation on Devsite is outdated. @joelibaceta please update it. @LukasMeine please use the Wiki on this Repository that it is up to date for the moment. Cheers!

**Comment by paulogdm** [comment]
@arielfr I have been digging  the source code of this SDK. It is really possible to use MP Connect with it? I mean, I need to configure the `accessToken` of my "seller", but the access_token in the SDK is a global variable! Following the function `getCredentialsAndConfigure` it seems to have problems with race condition (because of the access_token variable).

**Comment by arielfr** [comment]
@paulogdm Yes, the MercadoPago SDK Works as a Singleton. It's like using a `mongodb` or `postgresql` SDK, you configure the credentials onces. In case of MP Connect we are working to provide a way to override the credentials on the `request` you're doing to use the once you choose. So, the SDK is configure with your credentials BUT, you can choose to use another access_token depending on the operation you want to do.

**Comment by paulogdm** [comment]
@arielfr thank you for your response! The documentation on your website for MPConnect does not reflect the current state of the SDK. Do you think it is good to open an issue for that?

**Comment by arielfr** [comment]
It's a good idea. In the meanwhile, I'm creating an issue on GH
