### ISSUE TITLE
NPM Audit show 6 vulnerabilities

### ISSUE THREAD

**Issue by paulogdm** [mercadopago/dx-nodejs#115]
**Describe the bug**
By executing `npm audit` you can see that the mercadopago package has 6 vulnerabilities:

- 5 **moderate**:
 - [ ] hoek ( mercadopago > request > hawk > boom > hoek )
 - [ ] hoek ( mercadopago > request > hawk > cryptiles > boom > hoek )
 - [ ] hoek ( mercadopago > request > hawk > hoek )
 - [ ] hoek ( mercadopago > request > hawk > sntp > hoek )
 - [ ] tunnel-agent ( mercadopago > request > tunnel-agent )
- 1 low:
 - [ ] moment ( mercadopago > moment ) 

**To Reproduce**
1. Execute `npm audit` in a project that has mercadopago as a dependency.

**Expected behavior**
No output when executing `npm audit`.

**Screenshots**
[https://imgur.com/a/F3VO4rl](https://imgur.com/a/F3VO4rl)

**Server (please complete the following information):**
 - NodeJS Version: v9.x.x and v8.x.x
 - Operating System: Manjaro x64 (rolling release)

**Additional context**
Fix proposed: Perform `npm audit fix`. Since you don't have CI running for PRs, I feel that it is safer if one of MP's devs fix the issue checking for possible upgrade miss behaviors.

**Comment by arielfr** [comment]
@paulogdm Yes we do!
