### ISSUE TITLE
Alert of invalid CVC

### ISSUE THREAD

**Issue by vlimag** [mercadopago/dx-nodejs#118]
Hi,
I would like to know if is there a way to recognize invalid CVC/CVV before generating the token on android/ios sdk's, or even after generating it.

What we are current doing is:
- Generate token with React Native and Android/IOS modules
- Send the token to the back end (nodejs)

Doing that, we only figure it out that the payment wasn't accepted after some time.
If we could alert the user about incorrect CVC/CVV at the payment moment would be real time saving for the process.

Thanks

**Comment by arielfr** [comment]
Hi,

No, the only way to check if the CVC or CVV is correct is actually doing a payment. This is not a MercadoPago requirement is how Credit Card works, you can validate the length, but if it is actually correct is imposible to do it without making the payment 😛. You can implement our Android or Iphone SDK for Checkout (We do all the work, congrats, rejections, etc...)

Cheers!
