### ISSUE TITLE
Plans and Subscriptions

### ISSUE THREAD

**Issue by ezequieltejada** [mercadopago/dx-nodejs#119]
**Is your feature request related to a problem? Please describe.**
There is a method "plan" in the [documentation](https://www.mercadopago.com.ar/developers/es/guides/subscriptions/api/create-subscription) but it is not implemented

**Describe the solution you'd like**
I would implement it.

**Describe alternatives you've considered**
Doing it with a REST client directly.

**Additional context**
THIS DOESN'T EXIST.
![image](https://user-images.githubusercontent.com/4989765/44814303-a8d72300-abb2-11e8-9018-24291b84cb29.png)

**Comment by fedetango** [comment]
No es lo único! tanto **mercadopago.subscription** como muchos otros métodos documentados no existen en el SDK. La documentación y el SDK carecen de coherencia y tienen miles de faltas... la verdad es que lamentablemente es un desastre. Ya ni se entiende que partes de la api estan descartadas y cuales no. La referencia de API también esta incompleta.
Chicos, pilas, son los únicos en latinoamerica que ofrecen una herramienta de este tipo tan completa pero es lamentable que se tenga que hacer tanto esfuerzo para programar con su API.

**Comment by arielfr** [comment]
Por el momento suscripciones no lo vamos a soportar con la SDK de NodeJS. Habría que usar las APIS. Esta SDK provee un método para hacer requests.

**Comment by stiagocab** [comment]
Hola buen día, ya están habilitadas las suscripciones para Colombia o México, no encuentro la documentación especifica para realizarlas, solo pagos simples
