### ISSUE TITLE
Como obtengo un token de tarjeta de credito con esta api?

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [mercadopago/dx-nodejs#120]
estoy tratando de utilizar esta api con reactjs pero no encuentro como tokenizar una tarjeta de credito. 
otra cosa es puedo agregar el customer pero cuando trato de agregar una tarjeta al customer aparece esto: 
 name: 'MercadoPagoError',
  message: 'invalid parameters ',
  cause: [ { code: '119', description: 'the card is required' }

mis parametros son: 
 var card={
          id:'1',
          customer_id:'164612381-C3gk8oDC5NbRrD',
          card:{
            id:'54585469521425496852684593',
            expiration_month: 05,
            expiration_year:2020,
            first_six_digits:'123456',
            last_four_digits:'1234',
            date_created:25/8/17,
            cardholder:{
              identification:{
                number:'8045688',
                type:'DNI',
              },
              name:'Iris fernandez'
             }
          },
          payment_method:{
            name:'visa',
            payment_type_id:'visa',
           },
           security_code:{
             lenght:3,
             card_location:'151',
           },
          
        }
        mercadopago.customers.cards.create(card).then(function (mpResponse) {
          console.log(mpResponse);
        }).catch(function (mpError) {
          console.log(mpError);
        });

**Comment by jessk77** [comment]
Hola, tambien quiero sacar el token en react, has podido hacerlo?

**Comment by joelibaceta** [comment]
@GolfredoPerezFernandez @jessk77 Por motivos de cumplimiento con la normativa PCI, no se permite la tokenizacion del lado del servidor si fuera de un entorno PCI Compliance, por lo que este SDK no abstrae este Endpoint, para tokenizar por lo pronto se debe usar el SDK de JS para frontend ( El cual por lo pronto no soporta React).

**Comment by stiagocab** [comment]
Hay manera de tokenizar por medio del API reference? Estoy usando nativescript y no hay forms para poder usar el mètodo del sdk de js
