### ISSUE TITLE
Error: ".additional_info.shipments.receiver_address": should be string al crear pago

### ISSUE THREAD

**Issue by edmon1024** [mercadopago/dx-nodejs#123]
**Describe the bug**
Al intentar generar un pago con el checkout personalizado al agregar los datos adicionales, en este caso additional_info.shipments.receiver_address en additional_info, se lanza un error del tipo de dato, que es string en vez de objeto, cuando en la documentación esta marcado como objeto para agregar la dirección de envío.

**To Reproduce**
1. Crear el objeto para generar un pago, se lanza el error que no se pudo generar por el tipo de dato si se agregan los siguientes datos en "additional_info"

>         "shipments": 
>         {
>             "receiver_address":
>             {
>                 "zip_code": "23450",
>                 "street_name": "Calle",
>                 "street_number": "112"
>             }
>         }

**Expected behavior**
El resultado esperado era poder generar un pago con éxito

**Screenshots**
**Error recibido:**
> Error: The next fields are failing on validation: ".additional_info.shipments.receiver_address": should be string.

 
**Server (please complete the following information):**
 - NodeJS Version: 8.14.0
 - Operating System: fedora 27

**Additional context**
En la documentación se tiene marcado ese campo como **objeto**, pero en el modelo en el SDK de la versión 1.0.19 muestra que el campo "receiver_address" es un **string**

https://github.com/mercadopago/dx-nodejs/blob/e6d43f1fb994d00df15a0ff4a505cc84a694eb93/lib/models/paymentModel.js#L197

No se si sea de ese modo y estoy errando en algo, pero no coincide la información

En el ejemplo que se tiene se muestra un ejemplo básico, pero no con los datos completos ideales para generar un pedido sin problemas de rechazo:
https://github.com/mercadopago/dx-nodejs/blob/e6d43f1fb994d00df15a0ff4a505cc84a694eb93/examples/payment/create.js

**Comment by arielfr** [comment]
Hola @edmon1024 . Muchas Gracias por tu reporte. Te cuento que lo solucionamos hace un rato. Podes descargarte la nueva versión:

```
npm i mercadopago@1.0.20 --save
```

**Comment by edmon1024** [comment]
En la versión 1.0.21 realizarón un rollback para restaurar este cambio, entonces la documentación esta mal? porque receiver_address esta marcado como un objeto que contiene la información de la dirección.

Seria buena idea que su CHANGELOG lo actualicen con todos los cambios, y no solamente con el último, porque la documentación no coincide y podemos tener errores que llevaria tiempo resolver y no vemos documentación al respecto de cambios como este tipo para informarnos los datos correctos
