### ISSUE TITLE
basic checkout integration with React in frontend side

### ISSUE THREAD

**Issue by FernandWTF** [mercadopago/dx-nodejs#127]
Hey, Queria preguntar y/o sugerir una manera de generar un boton basico de checkout con react sin la necesidad de hacer una peticion a un api donde tenga un sdk de mercadopago.

Intente importar directamente el sdk en React y generar un link de pago con ``mercadopago.preferences.create``

pero me da el siguiente error
``` "SSL Error: https://api.mercadopago.com/checkout/preferences?access_token=TEST-4542114287084561-.... does not support SSL" ```

Estoy trabajando bajo un proyecto netamente sobre React + Firebase, nada mas. Para el 'backend' he tenido que usar las Firebase cloud functions y como podran intuir depronto no es lo mas intuitivo tener que hacer todo ese proceso solo para obtener un url que te lleve a mercadopago y haga el usuario haga el checkout.

Saludos.

**Comment by joelibaceta** [comment]
@FernandWTF actualmente no soportamos react de forma explicita. El error de SSL se debe a que no se esta usando un protocolo adecuado para comunicarse con el API de MercadoPago, se recomienda TLS mayor a la versión 1.0.

**Comment by sanjualechuzo** [comment]
@joelibaceta  cuando decis que no esta de forma explicita significa que no tiene componentes o acciones directas.. Pero si se puede implementar si uno genera las functions en react  y/o crea su propios componentes para usar  npm mercadopago ?

**Comment by LuKks** [comment]
Nada impide hacer un iframe con el init_point o realizar las requests correspondientes a la API.
Qué necesitás hacer exactamente?

**Comment by cdssanchez** [comment]
Hola me surge el mismo problema, necesito integrar para realizar un spit de pago..pero no logro hacerlo funcionar.
