### ISSUE TITLE
Error en documentacion

### ISSUE THREAD

**Issue by franciscomemoli** [mercadopago/dx-nodejs#129]
**Describe the bug**

En la documentación indican el siguiente método 

    Remove - Remove a card
`       mercadopago.customers.cards.remove(customer_id, card_id, configurations, callback)`

El cual no existe, el correcto es:
`       mercadopago.customers.cards.delete(customer_id, card_id)`

Algo similar ocurre con la creación de la tarjeta. Falta definir el payload correctamente:

```
const cardData = {
          "token": cardTokenId,
          "id": customer.response.id
        };
mercadopagoSdk.customers.cards.create(cardData)
```

**Comment by Juanii95** [comment]
Solved!
