### ISSUE TITLE
[sandbox] mercadopago.payment.search y get. no encuentran el pago pero con un get vía curl/postman sí.

### ISSUE THREAD

**Issue by maxicastro** [mercadopago/dx-nodejs#131]
Los métodos de la api mercadopago.payment.search y .get no encuentran el pago pero con curl sí lo encuentra.

```
// get - promise
mercadopago.payment.get(17734760).then(function (response_payment) {
            console.log(response_payment)
        }).then(function (error) {
            console.log(error)
        })
```
Unhandled rejection MercadoPagoError: Payment not found
    at Object.callback (...node_modules/mercadopago/lib/request-manager.js:320:19)

```
search - promise
var filters = {
            id: 17734760
        }
        mercadopago.payment.search({
            qs: filters
        }).then(function (data) {
            console.log(data)
        }).catch(function (error) {
            console.log(error)
        })
```
mercadopagoResponse {
  body: { paging: { total: 0, limit: 30, offset: 0 }, results: [] },
  response: { paging: { total: 0, limit: 30, offset: 0 }, results: [] },
  status: 200,
  idempotency: undefined,
  pagination: { total: 0, limit: 30, offset: 0 } }

```
// get - Callback
mercadopago.payment.get(17734760, {}, function(err, payment) {
            if (err) console.log(err)
            if (payment) console.log(payment)
        })
```

mercadopagoResponse {
  body: { paging: { total: 0, limit: 30, offset: 0 }, results: [] },
  response: { paging: { total: 0, limit: 30, offset: 0 }, results: [] },
  status: 200,
  idempotency: undefined,
  pagination: { total: 0, limit: 30, offset: 0 } }

// curl o postman

https://api.mercadopago.com/v1/payments/17734760?access_token=TEST-...

```
{
    "acquirer": null,
    "acquirer_reconciliation": [],
    "additional_info": {},
    "authorization_code": null,
    "binary_mode": false,
    "call_for_authorize_id": null,
    "captured": true,
    "card": {
        "cardholder": {
            "identification": {
                "number": "12345678",
                "type": "DNI"
            },
            "name": "APRO"
        },
        "date_created": "2019-02-08T10:45:35.000-04:00",
        "date_last_updated": "2019-02-08T10:45:35.000-04:00",
        "expiration_month": 2,
        "expiration_year": 2020,
        "first
```

**Comment by GonzaGr92** [comment]
Me paso algo similar pero para crear pagos. Si le estas pegando a la api desde http normalmente te bloquea la petición por el parámetro strictSSL (configuración seteada a la librería request desde request-manager)
Checkea cambiar la linea 285 de mercadopago/lib/request-manager.js

`req.strictSSL = true;`

por: 

`req.strictSSL = configurations.sandbox ? false : true;`

Por supuesto funcionaria siempre y cuando esté funcionando en sandbox.
Saludos.

**Comment by maxicastro** [comment]
@GonzaGr92 nada, apliqué lo de la línea 285 que nombraste y sigo igual.

1 - Creo la preferencia, me devuelve el link de pago: 

`https://sandbox.mercadopago.com/mla/checkout/pay?pref_id=235878668-c03151d3-b05c-47e6-87f6-18ef944314d9
`
2 - Recibo esto al ir al link de MP: 

`POST /ipn?id=993163878&topic=merchant_order`

3 - Realizo el pago exitosamente en MP

4 - Al realizar el pago recibo: 

`POST /ipn?data.id=18258446&type=payment`

Esto ya me genera un error

`Unhandled rejection Error: Invalid Topic (undefined). The topics available are: preapproval, authorized_payment, payment, merchant_order
    at Object.<anonymous> (/home/tienda/arteinfernal/tienda/node_modules/mercadopago/lib/resources/ipn.js:49:17)`

5 - Voy a buscar el pago con lo de data.id y nada

```
Called to mercadopago.payment.search(18258446)
mercadopagoResponse {
  body: { paging: { total: 0, limit: 30, offset: 0 }, results: [] },
  response: { paging: { total: 0, limit: 30, offset: 0 }, results: [] },
  status: 200,
  idempotency: undefined,
  pagination: { total: 0, limit: 30, offset: 0 } }
Called to mercadopago.payment.get(18258446) with callback
{ MercadoPagoError: Payment not found
    at Object.callback (....../node_modules/mercadopago/lib/request-manager.js:321:19)
    at Request._callback (......./node_modules/request-etag/lib/request-etag.js:72:18)
    at Request.self.callback (/home/tienda/arteinfernal/tienda/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> 
......
  name: 'MercadoPagoError',
  message: 'Payment not found',
  cause:
   [ { code: 2000, description: 'Payment not found', data: null } ],
  status: 404,
  idempotency: undefined }
Unhandled rejection MercadoPagoError: Payment not found
    at Object.callback (......node_modules/mercadopago/lib/request-manager.js:321:19)

```

**Comment by maxicastro** [comment]
Hola ! @GonzaGr92 con lo de strictSSL funcionó bien.
Gracias !
