### ISSUE TITLE
Ayuda para implementar correctamente Mobile Checkout

### ISSUE THREAD

**Issue by ernestojr** [mercadopago/dx-nodejs#133]
**Ayuda para implementar correctamente Mobile Checkout**
Hola chicos, me disculpo por dejar esto por acá, es que, en stackoverflow en español no vi mucho movimiento en el tag de mercadopago. Voy al grano, estoy haciendo una implementación de Mobile Checkout en Node y Android para un e-commerce. Mi backend crea la preferencia, la guarda en la orden de compra  y luego regresa la orden con las preferencias al cliente, este usa el id de la preferencia para continuar con el pago. Ahora, cuando realizo el pago (tarjetas de prueba), la respuesta me trae el id del pago, el cual lo envío al backend para actualizar la orden de compra. Mi problema es, cuando obtengo el pago (en backend), no encuentro algún campo que relacione ese pago con la preferencia creada previamente, necesito esto para de poder confirmar que el pago pertenece a una orden, no puedo relacionarlo con el id  la orden que me envía el cliente móvil porque eso sería una vulnerabilidad. Es posible que me estoy saltando algo, espero puedan ayudarme con eso. Muchas gracias.

**Comment by joelibaceta** [comment]
@ernestojr te comento, este no es un canal de soporte tecnico, te recomiendo usar el canal de soporte oficial para desarrolladores http://www.mercadopago.com.ar/developers/es/support/.
Este canal esta destinado unicamente para discutir bugs, errores o sugerencias sobre el SDK de NodeJS para MercadoPago.

**Comment by ernestojr** [comment]
Vale, Gracias por la información.
