### ISSUE TITLE
[Sandbox] Error 500 - an error occurred doing PUT card_token

### ISSUE THREAD

**Issue by maxicastro** [mercadopago/dx-nodejs#138]
**Describe the bug**
Al pagar en sanbox muestra un error "Ups, tuvimos un problema". La petición genera error 500 "an error occurred doing PUT card_token"

**To Reproduce**
1. Generar una preferencia de pago e ir a la pantalla de pago.
2. Completar los datos con una tarjeta de pago (en mi caso probé con varias de Argentina), usar usuario de prueba o sin usuario de prueba, el error es el mismo.
3. Presionar pagar.
4. Se muestra en pantalla el error "Ups, tuvimos un problema. Reintentar" y la petición devuelve
 `{"message":"an error occurred doing PUT card_token","status":500,"error":"internal_error","cause":[{"description":"an error occurred doing PUT card_token","code":"E702"}]}`

**Expected behavior**
Procesar el pago, disparar la IPN, redirigir a la pantalla de inicio.

**Screenshots**
![Selección_232](https://user-images.githubusercontent.com/5463813/54550253-6debdf80-498a-11e9-890d-32196a6a58a9.jpg)

 - NodeJS Version: 10.15
 - Operating System: Ubuntu 16.04

**Comment by joelibaceta** [comment]
@maxicastro el error 500 corresponde a una respuesta de error de parte del API durante el proceso de pago, te sugiero usar el [canal de soporte de MercadoPago](http://www.mercadopago.com.ar/developers/es/support/) para que puedan ayudarte con consultas de este tipo, este canal esta destinado únicamente a bugs o mejoras del SDK de NodeJS no al uso general de los productos de MercadoPago.
