### ISSUE TITLE
Preapproval con usuarios de prueba

### ISSUE THREAD

**Issue by lainz** [mercadopago/dx-nodejs#153]
Hola, quería preguntar si se pueden usar dos usuarios de prueba para realizar las suscripciones, este es mi codigo actual:

Yo le paso como parametros payer_email que es el mail del usuario de pruebas que se suscribe y la cantidad que debe pagar

```javascript
'use strict';

var mercadopago = require("mercadopago");

// uso client id y client secret de uno de los dos usuarios de prueba, el que recibe el pago, desde
// https://www.mercadopago.com/mla/account/credentials?type=basic
mercadopago.configure({
    client_id: '',
    client_secret: ''
});

export function mpsuscripcion(req, res) {

    console.log(req.body.payer_email)
    console.log(req.body.transaction_amount)

    var preapprovalPayment = {
        payer_email: req.body.payer_email,
        back_url: 'https://google.com',
        reason: 'Abono mensual',
        external_reference: 'Abono-0001',
        auto_recurring: {
            frequency: 1,
            frequency_type: 'months',
            transaction_amount: parseFloat(req.body.transaction_amount),
            currency_id: 'ARS',
            start_date: mercadopago.utils.date.now().add(1).toString(),
            end_date: mercadopago.utils.date.now().add(3).toString()
        }
    };

    mercadopago.preapproval.create(preapprovalPayment).then(function (data) {
        res.json(data)
    }).catch(function (error) {
        res.json({
            error: error
        });
    });
}
```

Cuando entro al enlace "init_point", lleno la tarjeta de pruebas
https://www.mercadopago.com.ar/developers/es/guides/localization/local-cards

Pongo el nombre del cliente como APRO para aprobar el pago, pongo DNI 12345678, 123 en clave de seguridad, acepto que me debiten mensualmente, hago clic en el botón para continuar y me sale "Ups, algo funcionó mal
Cierra e intenta nuevamente."

Que datos tengo que poner en DNI, y en clave de seguridad.

Ya venia usando mercadopago con pagos regulares con usuarios de prueba y andaba ok, acá no me estaría funcionando.

**Comment by LuKks** [comment]
Yo lo había resuelto probando directamente con usuarios reales porque en sandbox me tiraba el mismo mensaje que a vos.
Aunque recuerdo que una vez logré que sandbox funcione pero no pude repetir el movimiento, demasiado drama así que preferí olvidarme de sandbox.

**Comment by lainz** [comment]
Ah ok, gracias por confirmar.

**Comment by LuKks** [comment]
Probé nuevamente y no puedo.
Creé dos usuarios de prueba con mi access token de producción (de mi cuenta personal) tal como está ejemplificado.
https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/test-integration/

**Comment by LuKks** [comment]
Probé nuevamente y no puedo.

Creé dos usuarios de prueba con mi access token de producción (de mi cuenta personal) tal como está ejemplificado en https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/test-integration

Vendedor: test_user_27490405@testuser.com
Comprador: test_user_7065136@testuser.com

Después con el acess token de producción de uno de los usuarios de prueba generé la siguiente suscripción utilizando el email del segundo usuario de prueba:
https://www.mercadopago.com/mla/debits/new?preapproval_id=a6da47cf9a854cefbd73bb94c8d6169c

Utilicé una de las tarjetas de prueba y sucede el error ya comentado.

También hice el mismo procedimiento creando los dos usuarios de prueba con mi access token de sandbox pero resulta en lo mismo.

**Comment by LuKks** [comment]
Creando la suscripción desde la web con el usuario vendedor de prueba entonces funciona correctamente.
https://www.mercadopago.com.ar/subscription-plans

**Comment by LuKks** [comment]
Ahgg, ahora está funcionando pero fue después de haber creado la suscripción desde la web, al menos, a partir de ese momento empezó a funcionar.

@lainz sería genial que pruebes crear la suscripción tal como lo habías hecho y si sigue sin funcionar entonces probar crear desde la web manualmente, probás con esa que supuestamente debería funcionar y después volver a crear con código.

**Comment by lainz** [comment]
Claro igual la idea era crear la suscripcion por medio del usuario y actualizarla via codigo si cambiaran los precios, es decir que sea lo mas automatico posible.

**Comment by LuKks** [comment]
Comprendo pero tu issue es sobre utilizar usuarios de prueba con preapproval, en mi caso comenzó a funcionar correctamente después de crear una suscripción desde la web y probar esta misma, a partir de ahí el resto de suscripciones vía código funcionaron bien.

**Así que de nuevo al principio**, si te sigue sin funcionar vía código entonces deberías probar crear solamente una desde la web y ver qué pasa ya que parece un error medio extraño o una confusión nuestra.
Desde el vendedor de prueba: https://www.mercadopago.com.ar/subscription-plans/create
Después con el enlace acortado que te genera, usás una tarjeta de prueba y el email del comprador de prueba.
Yo usé: MasterCard, 5031 7557 3453 0604, 11/15, APRO, 41111111, 123, invitado (no login).

**Comment by lainz** [comment]
Ok entendido, voy a probar como me decís.

**Comment by lainz** [comment]
Probe como me dijiste haciendo una suscripción nueva desde la cuenta de pruebas desde la web y dando el link a otra cuenta de pruebas, pero dice "ups algo funciono mal", por lo menos a mi tampoco me funcionó de esa forma.

**Comment by LuKks** [comment]
![](http://i.imgur.com/gnugPKe.png)

Actualmente generé dos usuarios de prueba y creé la suscripción directamente desde Node y todo bien.

Lo que voy a hacer es dejarte directamente mis dos usuarios de prueba con exactamente el mismo código, están hechos con una segunda cuenta real que casi no utilizo.

Vendedor:
```json
{
    "id": 463598017,
    "nickname": "TETE474447",
    "password": "qatest6158",
    "site_status": "active",
    "email": "test_user_32824274@testuser.com"
}
```

Comprador:
```json
{
    "id": 463597522,
    "nickname": "TESTFOKZNAZR",
    "password": "qatest1847",
    "site_status": "active",
    "email": "test_user_45703644@testuser.com"
}
```

Usás el `init_point` generado:
```js
const mp = require('mercadopago');

mp.configure({
  //seller access token
  access_token: 'APP_USR-8007196929019694-082120-d3513f8dd2a0cfb92ac4168d14c0c3cf-463598017'
});

mp.preapproval.create({
  //buyer email
  payer_email: 'test_user_45703644@testuser.com',
  back_url: 'https://www.google.com',
  reason: 'Abono mensual',
  external_reference: 'Abono-0001',
  auto_recurring: {
    frequency: 1,
    frequency_type: 'months',
    transaction_amount: 40,
    currency_id: 'ARS'
  }
})
.then(data => console.log(data))
.catch(err => console.error(err));
```

Para el pago utilicé los datos que mencionados en mi anterior comentario.
> Yo usé: MasterCard, 5031 7557 3453 0604, 11/25, APRO, 41111111, 123, invitado (no login).

**Comment by lainz** [comment]
Será que yo accedo con client_id y client_secret en vez del access_token?

**Comment by LuKks** [comment]
Lo había notado pero no creo porque:
> We highly recomend using only the access_token. If you provide the client_id and client_secret it's going to generate the access_token anyway (only on Production, for Sandbox use access_token).

Además, yo usaba directamente el access token e igual tenía el problema.

**Comment by lainz** [comment]
Ok. Estoy intentando realmente con la preferencia que cree desde la web, pero no entiendo como puedo hacerlo como invitado (no login) si me pide el correo electronico de todas formas?

**Comment by LuKks** [comment]
No pide correo, es opcional:
![](http://i.imgur.com/rw0iBy8.png)
Solamente no ingreses ahí, podrías probar abriendo una ventana en incógnito.

**Comment by LuKks** [comment]
Intentá pagar esta directamente:
https://www.mercadopago.com/mla/debits/new?preapproval_id=e37b2a0cc0a14bd7bcda8ee1e690ebb9

También podés generar una nueva con el último código que comenté, ya tiene un `access_token` establecido.

**Comment by lainz** [comment]
Si ahi me anduvo, el tema que no entiendo es si creo una preferencia desde la web nada mas, me sale con el campo mail y ahi ya no puedo probar cada vez que le pongo el mail no me deja y me tira en rojo, no me sale como con tu preferencia que tiene el login. Me sale un campo email.

Voy a probar de la otra forma, creando la suscripcion via codigo con el access token.
![mp](https://user-images.githubusercontent.com/4131395/63469929-b92a8280-c441-11e9-811d-6698a0b43ccc.PNG)

**Comment by lainz** [comment]
Muchas gracias ahi me anduvo la suscripción con usuarios de prueba! En el código que tenia lo unico que hice fue usar el access_token de producción, el resto lo dejé igual y así me funcionó.
