### ISSUE TITLE
Recibir notificaciones de pagos de suscripciones

### ISSUE THREAD

**Issue by lainz** [mercadopago/dx-nodejs#154]
Hola, si ya tengo suscripciones mensuales en una cuenta de MP, como hago para recibir las notificaciones que se recibió el pago?

Actualmente tengo una pagina para ver si se realizaron los pagos normales, este es el código, quiero saber si esa pagina así como esta me sirve o que código tengo que usar y donde lo configuro en mi cuenta de MP (si es que es otra pagina).

```javascript
'use strict';
// configurar URL notificacion
// https://www.mercadopago.com.ar/ipn-notifications

export function notificaciones(req, res) {
    var request = require("request");
    var url = require("url");
    var MP = require("mercadopago");
    console.log(req)
    // client id, client secret
    // https://www.mercadopago.com/mla/herramientas/aplicaciones

    var mp = new MP("client id","client secret");

    var params = url.parse(req.url, true).query;

    var topic = params.topic;

    switch (topic) {
        case "payment":
            mp.get("/collections/notifications/" + params.id).
                then(function (payment_info) {
                    mp.get("/merchant_orders/" + payment_info.response.collection.merchant_order_id)
                        .then(processMerchantOrder);
                });
            break;

        case "merchant_order":
            mp.get("/merchant_orders/" + params.id)
                .then(processMerchantOrder);
            break;

        default:
            processMerchantOrder(null);
    }

    function processMerchantOrder(merchant_order_info) {
        if (merchant_order_info == null) {
            throw "Error obtaining the merchant_order";
        }

        if (merchant_order_info.status == 200) {

            // retorna payments
            /*

[ { id: 3044525359,
    transaction_amount: 400,
    total_paid_amount: 400,
    shipping_cost: 0,
    currency_id: 'ARS',
    status: 'approved',
    status_detail: 'accredited',
    operation_type: 'regular_payment',
    date_approved: '2017-10-09T13:31:41.000-04:00',
    date_created: '2017-10-09T13:31:41.000-04:00',
    last_modified: '2017-10-09T13:31:41.000-04:00',
    amount_refunded: 0 } ]


    https://www.mercadopago.com.ar/developers/es/api-docs/basic-checkout/merchant-orders/

    external_reference = id de abono
            */
            /*console.log(merchant_order_info.response.payments);
            console.log("ID ABONO:");
            console.log(merchant_order_info.response.external_reference);
            console.log(merchant_order_info.response.shipments);
            */
            console.log(merchant_order_info.response.payments[0]);

            // https://www.mercadopago.com.ar/developers/es/guides/payments/api/handling-responses
            if (merchant_order_info.response.payments[0].status == 'approved') {
                request(
                {
                    .. reporto el pago internamente
                },
                function (error, response, body) {
                    if (error) {
                        return console.error('failed:', error);
                    }
                    console.log('ok:', body);
                })
            }
        }
    }
    res.sendStatus(200);
}
```

**Comment by lainz** [comment]
Veo que acá tienen un ejemplo, como adaptarlo a la pagina que ya tengo funcionando?

https://github.com/mercadopago/dx-nodejs/blob/master/examples/instant-payment-notifications/receive-ipn.js

**Comment by LuKks** [comment]
Ya lo solucionaste? Yo tengo implementado suscripciones en mi sistema y realmente fue un drama hacer múltiples pruebas para realmente entender el flujo de notificaciones pero al final logré algo coherente y simple.
Capaz pueda hacer una librería para simplificar el uso de las notificaciones pero prefiero que me digas si realmente lo necesitás entonces le doy prioridad.

**Comment by lainz** [comment]
Estaria muy bueno tener esa librería, ya que no pude solucionarlo, mas como comenté en el otro hilo que no puedo probar con usuarios de prueba, hace que sea complicado trabajar.

**Comment by LuKks** [comment]
En lugar de armar una librería estaba armando un archivo medio completo con ejemplos pero me preguntaba si solamente necesitás saber cuando un pago fue aprobado y nada más?

Por ejemplo, también querés una request para crear una suscripción nueva y otra request para cancelar? Es decir, así los usuarios realizan esas acciones.

Tenés un front-end donde mostrás el estado de la suscripción (pendiente, autorizado, cancelado, etcétera)?
Lo mismo para el pago (procesando*, aprobado, etcétera)?
Mostrás la fecha del siguiente cobro?

Por ejemplo, en mi front-end necesito mostrar cuando el pago se está procesando porque demora 2 días hábiles cuando se trata de una suscripción, además del resto de información (datos de tarjeta, siguiente fecha, etcétera).

Quizás una librería no haga falta pero resulta confuso que haya que manejar 3 objetos distintos (preapproval, authorized_payment y payment). Sobre todo el authorized, ese pudo estar unificado con payment :/

Pero si ya tenés las suscripciones y solamente te interesa registrar los pagos aprobados entonces es realmente mucho más simple, se trata como un pago normal como cualquier otro.

**Comment by lainz** [comment]
Los ejemplos que mas puedas brindar, ya que son bastante escasos en este repositorio.

Pero en realidad lo que necesito es
- Crear la suscripcion con el usuario, yo le paso el monto a pagar
- Actualizar la suscripcion si cambia el monto
- Recibir notificacion del pago para ese usuario, con el mail como campo de verificacion o algun otro que se use al crear la suscripcion
- Informar cuando se le va a debitar el pago
- Cancelar la suscripcion

Si tenemos un frontend donde iria todo esto. Por ahora tenemos implementado el pago con mercado pago pero mes individual.

**Comment by LuKks** [comment]
Aclaro que no es tan simple porque básicamente estás pidiendo ayuda para toda una implementación de cero donde hay muchos factores a considerar entonces puede resultar complicado y más si se quiere hacer bien.
Por dar un ejemplo, tenés que tener en mente que alguien podría cancelar su suscripción (o incluso pausarla) directamente desde el panel de MercadoPago (fuera de tu plataforma) y más detalles.

**Ejemplo completo para crear, cancelar y manejar notificaciones**:
https://gist.github.com/LuKks/4bd0104a4c6e622a054a9580d9370032

Intenté reunir mis archivos en uno solo así que quedó un poco extenso pero solamente tenés que ir mirando parte por parte, realmente está de alguna manera dividido. Hay muchos comentarios y puede dar la sensación de mucho código, lo único que capaz no te sirve o hay alguna otra solución es el fix para el expire_date pero lo dejé aclarado.

Para cualquier ruta tenés que añadir tus propias condiciones como validar email y demás.

Dentro de las rutas, me refiero a `/new` y `/cancel`, podés notar que no aclaro sobre actualizar la base de datos, por ejemplo, después de crear una suscripción o cancelarla, esto es porque cuando vos hacés `mp.preapproval.create` y otras operaciones también se dispara la notificación entonces todos esos movimientos de la base de datos están manejados en `/ipn`.

No lo probé pero está basado en la implementación actual de mi sistema, incluso un poco mejor en unos detalles.
Teóricamente si no fallé en ningún error de sintáxis o error lógico, deberías poder realizar `/new` y `/cancel` además de ver logs coherentes sobre el proceso.
Utilicé simple objetos que intenta equivaler a una base de datos.
La idea no es copiar y pegar sino que lo implementes de a poco ya que aunque el código falle en algo, igual sirve de guía.

Explico en español la intención de dos rutas
`/new`:
* Cuando un plan ya está `authorized` entonces el usuario tiene que manualmente realizar `/cancel` porque, al menos yo, le pido el motivo y confirmación vía contraseña.
* Si está `cancelled` no hay necesidad de recancelarlo.
* En caso de que no esté `authorized` ni `cancelled` entonces quizás está en `pending` u otro estado en el cual podemos forzadamente cancelar omitiendo el `/cancel` formal.
* Después de las anteriores consideraciones, se crea el `preapproval` de forma normal.

`/cancel`:
* Si el usuario no tiene ninguna suscripción obviamente no hay nada para cancelar.
* Si está `cancelled` entonces lo mismo que antes.
* Después de las anteriores consideraciones, se cancela normal.
* Al cancelar la suscripción, también se cancelan pagos pendientes, en proceso y demás (recordá que demoran 2 días hábiles en aprobarse) pero los que ya estén aprobados no son devueltos ni cancelados.

Y una aclaración con respecto a la siguiente ruta
`/ipn`:
* Ya lo comenté mucho directamente en el código.
* Lo más importante es que está principalmente dividido en tres condiciones para separar cada topic (preapproval, authorized_payment y payment).
* Considerando lo anterior, el código dentro del topic payment no tiene que ver con los otros dos, etcétera. Idealmente después lo separás en múltiples funciones para mayor organización.
* No lo separé de entrada porque complicaba y extendía mucho el ejemplo sino tenía que pasar el objeto user y otras variables, crear más funciones, etcétera.

**Ejemplos para front-end**:
https://gist.github.com/LuKks/af2f8f3836c63f4f4dcdd0950f5fa787

**Ejemplos de notificaciones**:
https://gist.github.com/LuKks/054287337a9ac913bf0ab707b0ec2661

Tenés que notar que, por ejemplo, el payment fue con account_money pero hay datos de una card, es para que el mismo ejemplo sea más completo. Casi al final de `/ipn` está aclarado más sobre esto.

**Te recomiendo empezar así**:
https://gist.github.com/LuKks/07dd061832bc56bc40516fe107308b86

* Ahí solamente tenés que tener en cuenta que manejo `authorized_payment` dentro de `payment` porque según pruebas de hace meses la notificación de `authorized_payment` solamente me llegaba una sola vez.

**En fin**:
Todo esto sirve para manejar tanta información como es posible pero, por ejemplo, dependiendo algunos detalles podés remover todo lo relacionado a `authorized_payment` o conservar algunos datos del `authorized_payment` dentro del `preapproval` así te ahorrás una colección/tabla y bastante código.

Otro ejemplo es que podrías evitar tener un preapproval_id en el objeto user si directamente buscás entre las suscripciones `owner == userid && status != cancelled`. Así un usuario puede tener múltiples suscripciones o sencillamente evitás duplicar información.

Sé que es mucho texto pero intenté ser lo más completo posible. Como dije al principio, estás pidiendo ayuda para armar todo un sistema.

**Comment by lainz** [comment]
Muchas gracias por tu código, se ve todo muy completo. Si alguien de MP lo lee deberían incluirlo junto con los ejemplos de este repositorio, para que otro que lo necesite lo pueda encontrar también.

Muchas gracias por tu tiempo, espero tener éxito en el desarrollo. Saludos.

**Comment by lainz** [comment]
Probé con el codigo de backend_simple.js y el problema que tuve fue algo raro, ya que no pude configurar la URL de notificaciones en mercado pago (será por el async?). Cambié en el código res.send('') por res.sendStatus(200) sino me decia que la pagina debia devolver status 200. De todas formas no pude probar por el tema de los usuarios de prueba que no funcionan.

**Comment by LuKks** [comment]
`async` no tiene relación con el problema porque es solamente para evitar hacer `then` y anidar callbacks.

Seguramente sí pero notaste que es un router de Express? Tenés que:
```js
app.use(require('./backend_simple.js'));
```

Tendrías que usar `/new/:email` para comprobar que las rutas están funcionando y además se crearía una preferencia para probar si llega la notificación.

Con respecto al status, se supone que por defecto es 200 y con `res.send` es suficiente, de hecho, lo tengo funcionando de esa forma.

Tal como dijiste, primero sería mejor aclarar el otro asunto.

**Comment by lainz** [comment]
Ok, el tema era que mi versión de node parece que no soporta async y await, o alguna configuración que tengo de express.

Lo cambie por then..catch y al menos lo pude configurar en la pagina de ipn de mercado pago.

**Comment by LuKks** [comment]
En la v7.10 hay async/await, estamos en v12.9, qué te impide actualizar? Lo pregunto por curiosidad, se supone que dx-nodejs es compatible con versiones antiguas.
Anidar then y catch no está bueno, con tener 5 operaciones ya se vuelve terrible de mantener.

Entonces pudiste? Probaste usando directamente el access token?

**Comment by lainz** [comment]
Tenemos la 8.9.3, pero de todas formas no funcionaba el codigo. Debe ser otra cosa. Yo no manejo la version de node que esta instalada, estamos usando AWS.

Llegaron las notificaciones con usuarios de prueba ahora vamos a ver en produccion.

**Comment by lainz** [comment]
Funcionó perfecto en producción también. Muchisimas gracias por tu gran ayuda.
