### ISSUE TITLE
No funcionan los pagos

### ISSUE THREAD

**Issue by lainz** [mercadopago/dx-nodejs#159]
Hola, los pagos venian funcionando correctamente, pero ahora todos los usuarios tienen problemas al pagar, por mas que lo llevamos a la página de MP y llenan los campos no se puede efectuar el pago, este es el código que usamos para llevarlos a la página de pagos:

```JavaScript
'use strict';

export function pagos(req, res) {
    var MP = require("mercadopago");
    var mp = new MP("", "");
    var preference = {};

    var item = {
        id: '0001',
        title: req.body.detalle,
        quantity: parseInt(req.body.cantidad),
        currency_id: req.body.moneda,
        unit_price: parseFloat(req.body.total),
    }

    var payer = {
        email: req.body.mail
    }

    preference.external_reference = req.body.id; // external_reference: Reference you can synchronize with your payment system
    preference.items = [item]
    preference.payer = payer

    mp.createPreference(preference).then(function(data) {
        res.redirect(data.response.init_point);
    }).catch(function(error) {
        res.send(`
    <!DOCTYPE html>
    <html>
        <head>
            <title></title>
        </head>
        <body>
            Error de Mercado Pago: No se puede iniciar el pago. *Nota: No se realizó ninguna transferencia de dinero.
            <textarea style="width: 100%" rows="10">${error}</textarea>
        </body>
    </html>
    `);
    });
}
```

**Comment by lainz** [comment]
Nota: con usuarios de prueba funciona correctamente, eso es lo raro, con usuarios reales es donde falla.

**Comment by LuKks** [comment]
Sería genial un código reproducible, es decir, que yo pueda copiar, pegar y ejecutar para replicar el problema, quizás únicamente cambiar credenciales.
Ya que "problemas al pagar" no es muy específico, **siempre se necesita un código que replique el problema de ser posible, así es más fácil ayudar**.

**Comment by lainz** [comment]
Ese es el codigo tal cual lo tengo en el sitio, asi que ese es el que tiene problemas.

Los parametros son sencillos, detalle, cantidad, moneda, total, mail, se pueden reemplazar facilmente. Para moneda uso siempre 'ARS', la referencia es un uuid que para probar puede ser cualquiera.

Lo tengo armado como podes ver con la vieja api,
var mp = new MP("", ""); // client id y client secret

Aunque sigue funcional el tema de enviar al usuario a la pagina de pagos, puede que ya no se pueda hacer de esta forma.

El tema es que con usuarios de prueba funciona ok.

**Comment by lainz** [comment]
Edit: funcionaba ok, ahora que me acuerdo ayer probe y dejo de andar con usuarios de prueba también, lo mas probable es que haya sido reemplazada con pagos con tarjeta que esta como hacerlo en la web de desarrollo, y esto haya dejado de andar.

**Comment by LuKks** [comment]
Yo sé que es sencillo, el código reproducible era para vos mismo, no para mí.

![](http://i.imgur.com/md2oDlL.png)
```js
const MP = require('mercadopago');
let mp = new MP('111', 'aaa');

mp.createPreference({
  payer: {
    email: 'mp@amail3.com'
  },
  external_reference: 'extref',
  items: [{
    id: '0001',
    title: 'Mi producto',
    quantity: 1,
    currency_id: 'ARS',
    unit_price: 40.0
  }]
})
.then(console.log)
.catch(console.log);
```

También lo probé directamente con `access_token` tanto sandbox como producción y todo funciona.

**Comment by lainz** [comment]
Ok gracias por probarlo. Voy a ver qué puede ser.

**Comment by lainz** [comment]
Volvio a funcionar sin tocar el código, así que no era problema de nuestra parte, sino de MP, quizas si con nuestra cuenta, pero quien sabe.
