### ISSUE TITLE
Actualizar monto de la suscripción via codigo y external_reference

### ISSUE THREAD

**Issue by lainz** [mercadopago/dx-nodejs#160]
Es posible una vez realizada una suscripción via código, actualizar el monto de la suscripción también vía código, usando como filtro de busqueda la external_reference?

Porque por ejemplo nosotros tenemos planes mensuales que son individuales para cada cliente, tenemos un id que identifica al cliente y eso lo usamos para crear las suscripciones, entonces nuestro external_reference que nos llega en las notificaciones es el id del cliente.

Necesitamos automatizar el aumento o disminución en los montos mensuales a pagar por el cliente de las suscripciones existentes.

**Comment by LuKks** [comment]
https://github.com/mercadopago/dx-nodejs/issues/157

**Comment by lainz** [comment]
Gracias, ya lo pude solucionar. Por las dudas dejo como lo hice:

Obtengo el id de la preferencia:
GET https://api.mercadopago.com/preapproval/search?access_token=APP_USR&external_reference=uuid

Y actualizo el monto:
PUT https://api.mercadopago.com/preapproval/:id?access_token=APP_USR

Por el momento no almaceno el id de la preferencia, solo la external_reference, me es mas sencillo asi.

**Comment by LuKks** [comment]
Oh, preapproval, yo pensé en preference por eso mencioné el otro issue.

**Comment by LuKks** [comment]
> GET https://api.mercadopago.com/preapproval/search?access_token=APP_USR&external_reference=uuid

Podés probar tener dos preapproval con distintos external_reference y buscar solo uno?

Lo intenté pero aparecen todos los preapprovals así que tendrías que tener cuidado con actualizarle el monto a otros, es como que no funciona el filtro aunque debería porque está documentado.

**Comment by lainz** [comment]
Igual lo trabajamos una vez por mes o cuando cambian los costos, así que bajamos todo y filtramos el array nomas.

**Comment by LuKks** [comment]
Yep, es lo que hacía pero idealmente evitaría hacer múltiples requests. Guardar el id lo arreglaría aunque es extraño que no funcione el search, el resto de filtros funcionan bien, es solamente la ext ref.

**Comment by lainz** [comment]
Claro en realidad hago solo 1 request. Porque actualizamos todos una vez al mes nomas. En teoría porque nos volvió a funcionar el tema del pago mensual individual, asi que casi no usamos las suscripciones. Las que tenemos las seguimos manejando individualmente a mano por asi decirlo son muy pocas y no tienen el external reference, son creadas desde la UI de MercadoPago.
