### ISSUE TITLE
Uso no autorizado de credenciales de producción - Unauthorized use of live credentials

### ISSUE THREAD

**Issue by luchobertello** [mercadopago/dx-nodejs#161]
Buenas, estoy integrando Mercado Pago a través de la funcionalidad Marketplace (estoy utilizando el SDK de NodeJS).
Ya solicité la homologación y tengo las credenciales de producción, además de tener creada la aplicación de Marketplace.
A la hora de intentar realizar un pago obtengo el siguiente error:

**{
    "message": {
        "name": "MercadoPagoError",
        "message": "Unauthorized use of live credentials",
        "cause": [
            {
                "code": 7,
                "description": "Unauthorized use of live credentials",
                "data": null
            }
        ],
        "status": 401,
        "idempotency": "35b487b1-57fe-4f89-b477-5812ed05ca7d"
    },
    "code": -1
}**

Estoy haciendo exactamente lo mismo que indica la documentación con el SDK de NodeJS:

var mercadopago = require('mercadopago');
mercadopago.configurations.setAccessToken([ACCESS TOKEN DEL VENDEDOR ASOCIADO AL MARKETPLACE]);

var payment_data = {
  transaction_amount: 100,
  token: '[[TOKEN DE LA TARJETA OBTENIDO USANDO LA PUBLIC KEY DE LA CUENTA PRINCIPAL QUE COBRA LA COMISIÓN (NO DEL VENDEDOR)]]'
  description: 'Title of what you are paying for',
  installments: 1,
  payment_method_id: 'visa',
  user_token: "ENV_USER_TOKEN" --> NO PUEDO ENVIAR ESTE ATRIBUTO YA QUE ME DA UN ERROR DE QUE NO EXISTE
  payer: {
    email: '[[EMAIL DEL COMPRADOR]]'
  }
};

mercadopago.payment.create(payment_data).then(function (data) {
  // Do Stuff...
}).catch(function (error) {
  // Do Stuff...
});

Siguiendo los pasos de la documentación (https://www.mercadopago.com.ar/developers/es/guides/marketplace/api/create-marketplace/) continúo con el mismo error.
Por favor si alguien implementó Marketplace alguna vez o si alguien referido a Mercado Pago lee el mensaje se lo agradecería si puede darme una ayuda.

Gracias.
Saludos.
Luciano.

**Comment by theprometeus** [comment]
Estoy yendo el memo problema cuando yo hago una tentativa de devolver el pagamento de uña autorización.

También cuando yo tentó hacer un pagamento con la misma tarjeta de crédito salva en Mercadopago más de una vez, el API retorna "invalid token"

**Comment by federicosan** [comment]
Estás usando https en el dominio?

**Comment by luchobertello** [comment]
Si. Usamos https porque ML lo solicita para estar en producción.

**Comment by luchobertello** [comment]
Parece ser que el uso de credenciales no estaba de la manera correcta.
Se deben usar siempre las credenciales del vendedor y nunca las de la cuenta "host" de los pagos (en el caso de pago distribuido).
No está aclarado esto en la documentación pero la solucion es la mencionada anteriormente.
Cierro la issue. Gracias!
