### ISSUE TITLE
'Ops, ocorreu um erro.' Preferences in mercado pago Node SDK

### ISSUE THREAD

**Issue by Gutyerrez** [mercadopago/dx-nodejs#166]
I'm trying to create one preference and get payment link, but i open the payment link and that returns to this page: https://imgur.com/a/QEhV0KD

My code here:

```
const mercadopago = require('mercadopago');
const config = require('../config.json');
const access_token = config.mercadopago.access_token;

// Setup access token to mercadopago SDK

mercadopago.configure({
    access_token
});

  var preference = {
    items: [
      {
        title: 'Test',
        quantity: 1,
        currency_id: 'ARS',
        unit_price: 10.5
      }
    ]
  };

mercadopago.preferences.create(preference)
.then(result => {
    console.log(result)
})
.catch(console.error);

class MercadoPago {
    constructor(items) {
        this._items = items;
    }

    finalize() {
         // TODO not implemented
    }
}

module.exports = MercadoPago;

**Comment by LuKks** [comment]
Check https://github.com/mercadopago/dx-nodejs/issues/165#issuecomment-538288308

**Comment by Gutyerrez** [comment]
> Check [#165 (comment)](https://github.com/mercadopago/dx-nodejs/issues/165#issuecomment-538288308)

I tried all comment in this issue, but i don't got success 😢

**Comment by LuKks** [comment]
I will copy and paste the first code that I left in https://github.com/mercadopago/dx-nodejs/issues/165#issuecomment-540185854

Try this exact code:
```js
const mp = require('mercadopago');

//test seller user (production access token)
mp.configure({
  access_token: 'APP_USR-8007196929019694-082120-d3513f8dd2a0cfb92ac4168d14c0c3cf-463598017'
});

mp.preferences.create({
  items: [
    {
      title: 'Buying a PS4',
      unit_price: 10500,
      quantity: 1
    }
  ],
  payer: {
    //test buyer user (email)
    email: 'test_user_45703644@testuser.com',
    identification: {
      type: 'DNI',
      number: '41111111'
    }
  }
})
.then(console.log)
.catch(console.log);
```

The response includes:
`sandbox_init_point`: https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=463598017-3d109598-2f83-4b85-b0ea-7d18bbe64c89
But obviously also works with `init_point`.

Before pay, you need to login with:
![image](https://user-images.githubusercontent.com/12686176/66707669-72a72500-ed1a-11e9-84a7-f211dee9ac88.png)
Email: `test_user_45703644@testuser.com`
Password: `qatest1847`
Credentials are from here: https://github.com/mercadopago/dx-nodejs/issues/153#issuecomment-523646539

And just follow the payment process:
![image](https://user-images.githubusercontent.com/12686176/66707660-47243a80-ed1a-11e9-824e-4dea407d4385.png)

First I would recommend to test with the `sandbox_init_point` that I already left here, later try creating your own init point with the code.
