### ISSUE TITLE
dx-nodejs o sdk-nodejs?

### ISSUE THREAD

**Issue by rggdev** [mercadopago/dx-nodejs#78]
Buenas, estoy implementando con esta version (dx-nodejs), pero no estoy seguro si la podre usar para ir a produccion, ya que en [Sandbox/Checkout Basico] me da error luego de obtener las preferencias de pago.

Desde ya muchas gracias.
Saludos,
Roberto.

**Comment by joelibaceta** [comment]
Hola Roberto, la version dx-nodejs es la nueva sdk official, podrias indicar mas detalle sobre el error con la obtención de preferencias para confirmar si es un issue o bug en este sdk.

**Comment by rggdev** [comment]
Hola Joel, como les comentaba estoy trabajando con el sdk nuevo(dx-nodejs), al dia de la fecha tengo un feedback y 2 consultas.

El feedback es para la documentacion (Wiki) del IPN (https://github.com/mercadopago/dx-nodejs/wiki/IPN-Notifications), donde dice:
mercadopago.ipn.manager(request).then(function (response) {...
debe decir:
mercadopago.ipn.manage(request).then(function (response) {...

Por la consulta, tengo 2: 
1.-Cuando redirecciona al Checkout de MP (boton Pagar), ejecuta el POST del IPN (url indicada en la "Preferencia"), y devuelve 403 (se adjunta imagen). Pero en el Firewall tengo habilitado el puerto 443 para todas las IP, ya que estoy usando 'https'.

2.-La otra consulta es cuando realizo el pago en el Checkout de MP, me da siempre el mismo error: "Los usuarios son invalidos" (se adjunta imagen). Por lo que probe con 2 usuarios distintos, uno obtenido enviando mi Token.de Sandbox(curl), y otro enviando mis credenciales client_id/client_secret(curl).
Tambien probe con varias formas de pago (TC.de prueba, PagoFacil, Rapipago,etc), pero devuelve el mismo error.

Aqui les detallo mi codigo.
**router.js**
```
var express = require('express');
var router = express.Router();
var Cart = require('../models/cart');
var mp = require('mercadopago');

router.get('/checkout', function(req, res, next) {
  if (!req.session.cart) {
    return res.redirect('/');
  }
  var cart= new Cart(req.session.cart);
  var errorMsgs= req.flash('error');
  mp.configure({
    sandbox: true,
    client_id:'myID',
    client_secret:'mySECRET'
  });
  var products= cart.mpArray();
  var preference= {
    "items": products,
    "payer": {"email":"test_user_xxxxxxxx@testuser.com"},
    "payment_methods": {"installments": 12, "default_installments":1},
    "back_urls": {
      "success": "https://mydomain.com",
      "pending": "https://mydomain.com",
      "failure": "https://mydomain.com/webhook"
    },
    "notification_url":"https://mydomain.com/webhook",
    "auto_return": "approved",
    "external_reference": getRefToken()
  };
  mp.preferences.create(preference)
    .then(function(data) {
      res.render('button', {cart: cart, msgs: errorMsgs, preference: data, title:'Mercadopago'});
    }).catch(function(error) {
      res.send(error);
    });
});
router.get('/webhook', function(req, res, next) {
  mp.ipn.manage(req).then(function(data) {
    res.render('/webhook', {result: data});
    console.log('Ipn_Response:'+data);
  }).catch(function(error) {
    res.status(500).send(error.message+'\n'+req);
  });
});
router.post('/webhook', function(req, res, next) {
  var IpnTopic=req.params.topic;
  var IpnId=req.params.id;
  res.status(200).send('OK');
  if (IpnTopic =='merchant_order') {
    mp.ipn.merchant_orders(IpnId).then(function(ipnResponse) {
      console.log('Ipn_Response: '+ipnResponse);
    }).catch(function(error) {
      res.status(500).send(error.message+'\n'+req);
    });
  }
});
module.exports = router;
```
**button.pug**
```
doctype html
html
	head
		title= title
		link(rel='stylesheet', href='/stylesheets/style.css')
		block scripts
			script(src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js")
			script(type="text/javascript" src="/javascripts/checkout.js")
	body
		block content
			//-!PAGE CONTENT
			div(style="margin-top:83px; margin-left:50px;")
				h1 Pagar con Mercadopago
				img(src="https://imgmp.mlstatic.com/org-img/banners/ar/medios/785X40.jpg" title="MercadoPago - Medios de pago" alt="MercadoPago - Medios de pago" width="785" height="40")
				p
				ul(style="width:50%")
					li
						label Total: $ #{cart.total}
				p
				a(id="btnPay" href=""+preference.response.sandbox_init_point) Pagar
```

Desde ya muchas gracias.
Saludos,
Roberto.

**Comment by guillote22** [comment]
Hola Roberto! Yo tuve el mismo problema y lo resolví utilizando 2 usuarios de prueba, uno como vendedor y otro como comprador. Con lo cual, en "client_id" y "client_secret" deberías utilizar las credenciales del usuario de prueba vendedor. No sé si te es útil esta información. Espero que sí. Saludos!
Guillermo.

**Comment by rggdev** [comment]
![mperror-sandboxmode](https://user-images.githubusercontent.com/28788796/36034553-36c49c4c-0d93-11e8-80be-59e632d7f11f.png)

![mpcheckout-errusers2](https://user-images.githubusercontent.com/28788796/36034542-2a8bb1c2-0d93-11e8-99e2-5238140ebcd0.png)
Hola Guillermo, gracias por responder, efectivamente el usuario asociado a la app, no era vendedor, asi que active esa cuenta como vendedor(cuentaVendedor), y cree una cuenta nueva(cuentaComprador) en ML para obtener las credenciales de esta y obtener un usuario de prueba(test_user_69598756@testuser.com) = payer.

Ahora si tengo una cuenta(cuentaVendedor) para configurar el client_id/client_secret, y una cuenta nueva(cuentaComprador) para poner el email(test_user_69598756@testuser.com) del payer en la preferencia.

Lamentablemente sigo c'el mismo error: 'Los usuarios son invalidos'(se adjunta).

Aparentemente tengo un error en la cuenta Comprador, pero en la doc de la API dice que solo requiere el [email], que lo cree por curl como se indica en: (http://beta.mercadopago.com.ar/developers/es/guides/payments/web-checkout/testing/)

Por otro lado tengo otro feedback para la documentacion (Wiki) del [Sandbox Mode](https://github.com/mercadopago/dx-nodejs/wiki/Sandbox-Mode). Si hago la configuracion usando el token de la cuenta vendedor(asociada a la app), recibo un error "token not allowed"(se adjunta imagen), pero si me funciona(siempre en Sandbox), cuando uso el client_id/client_secret del vendedor.

Desde ya muchas gracias.
Saludos,
Roberto.

**Comment by joelibaceta** [comment]
Gracias @rggdev  por el feedback, tomamos nota y lo estaremos actualizando en la documentación.

**Comment by guillote22** [comment]
Hola Roberto! Te cuento como logré que funcione utilizando como modelo el código que subiste.
Primero, no uses el sandbox porque leí que no está funcionando. En la misma documentación propone como alternativa trabajar en modo producción con usuarios y tarjetas de prueba.
Lo que yo hice fue crear 2 usuarios de prueba, como dije antes, uno asociado a la app y otro como comprador. AMBOS SON DE PRUEBA. El error que te aparece, me apareció a mi cuando yo intentaba tener mi cuenta asociada a la app (yo soy un usuario real) e intentaba comprar con un usuario de prueba.
En el botón de pago no utilizo "sandbox_init_point", lo cambio a "init_point", trabajo en modo producción, no sandbox.
Y luego podes pagar si queres con alguna de las tarjetas de prueba que aparecen en la documentación.
Avisame como te fue.
Saludos.
Guillermo.

**Comment by rggdev** [comment]
Hola Guillermo, efectivamente ese era el error, estoy probando con ambos usuarios "TEST" en modo "Sandbox" y puedo cumplir el ciclo de compra completo.

Ahora estoy con el IPN ya que me sigue devolviendo 403.

Saludos y muchas gracias,
Roberto.

**Comment by guillote22** [comment]
Hola Roberto! Me alegro que puedas cumplir el ciclo de pago. Estuve viendo de nuevo tu código. En la ruta POST "/webhook", vi que tenes definida las variables IpnTopic e IpnId:
`var IpnTopic=req.params.topic;
  var IpnId=req.params.id;`

Sin embargo, en la captura del error 403 que enviaste, no se ve que hayan route parameters sino query strings. Con lo cual, creeria que "req.params.topic" y "req.params.id" son iguales a "undefined".
Habría que reemplazarlos de la siguiente manera:

`var IpnTopic=req.query.topic;
  var IpnId=req.query.id;`

Es lo primero que me llamó la atención, no se si resolverá tu problema, pero espero que ayude.
Saludos!!
Guillermo.

**Comment by rggdev** [comment]
Hola Guillermo, te paso una version mas "limpia" del router, porque el problema(403-Forbidden) creo que lo tengo en la configuracion de la app.
Es decir creo que lo que esta bloqueando el POST es alguno de los middleware que uso (express-session, express-validator, passport).
Por otro lado si hago un HEAD (cURL) me responde 201.OK(GET), solo tengo problema con el POST.

Esta es la configuracion (**app.js**)
`var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var session = require('express-session');
var passport = require('passport');
var flash = require('connect-flash');
var validator = require('express-validator');
var SQLiteStore = require('connect-sqlite3')(session);

var app = express();
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(validator());
app.use(cookieParser());
app.use(session({
    secret: 'myToken', 
    resave: false, 
    saveUninitialized: false,
    store: new SQLiteStore,
    cookie: { maxAge: 180*60*1000 }
}));
app.use(flash());
app.use(passport.initialize());
app.use(passport.session());
app.use(express.static(path.join(__dirname, 'public')));

app.use(function(req, res, next) {
    res.locals.login = req.isAuthenticated();
    res.locals.session = req.session;
    next();
});
require('./config/passport');
app.use(require('./routes/route'));
app.use(require('./routes'));

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});
// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  // render the error page
  res.status(err.status || 500);
  res.render('error');
});
module.exports = app;`

y este el route.js
`var express = require('express');
var router = express.Router();
//Este funciona OK
router.get('/webhook', function(req, res, next) {
  res.status(200).send('OK');
  console.log('200.OK, respuesta enviada a MP');
  res.end();
});
//Este no funciona (403 Forbidden)
router.post('/webhook', function(req, res, next) {
  res.status(200);
  console.log('200.OK: '+res);
  res.end();
});
module.exports = router;`

Saludos y muchas gracias,
Roberto.

**Comment by rggdev** [comment]
Buenos dias, con fecha 07/05/2018 complete el formulario para pasar la app a "Produccion", ya que actualmente se encuentra funcionando perfectamente (incluido Mercado Envios) en "Sandbox". Pero hasta la fecha no recibi ninguna respuesta de MercadoPago para poder pasarla a Produccion.

El formulario de solcitud(Produccion) se lleno con la cuenta simon (simoncobospr@gmail.com). Con esta cuenta obtuve las "Credenciales" para generar un usuario de prueba(TETE3832942) y asociar la app.(mp-app-319939414) a este ultimo usuario.

App ID:3450398956391583
Name:319939414 - MercadoPago application
Short Name:mp-app-319939414

Desde ya muchas gracias.

Saludos,
Roberto.

**Comment by joelibaceta** [comment]
@rggdev escribir a developers@mercadopago.com para soporte tecnico, este medio esta destinado únicamente a la discusión de issues o features del sdk para nodejs de Mercado Pago
