### ISSUE TITLE
Mercado pago no procesa los pagos utilizando el basic checkout (Tuvimos un problema, intenta nuevamente)

### ISSUE THREAD

**Issue by guillote22** [mercadopago/dx-nodejs#79]
Cada vez que presiono el boton "Confirmar Pago" en el Sandbox, aparece un mensaje que dice "Tuvimos un problema, intenta nuevamente".

He seguido los siguientes pasos:

1)Instalé la última versión del dx-nodejs de mercado pago.
2)Creé dos usuarios de prueba.
3)Utilicé mercadopago.configure({sandbox: true, access_token: 'ACCESS_TOKEN_DE_USUARIO_DE_PRUEBA_MODO_PRODUCCION'})
Antes de seguir, cabe aclarar que intenté usar el access_token del modo sandbox, mercadopago me respondía con un error que decía "Test tokens not allowed".
4)Creé la preferencia pensando en un checkout básico.
5) Me llega sin problemas la notificacion de merchant_order a la url que configuré en la preferencia.
6) Me logueo con el usuario de prueba COMPRADOR.
7) Ingreso una de las tarjetas de prueba con el prefijo APRO completando el resto de los datos como se indica en las instrucciones.
8) Aparece el mensaje "Tuvimos un problema, intenta nuevamente".

https://sandbox.mercadopago.com/mla/checkout/pay?pref_id=300565003-833b72ea-101b-4af3-9a8d-028878a628a6

He probado con distintas tarjetas, pero siempre ocurre lo mismo.
Esta deshabilitado el sandbox? Gracias!!

**Comment by KevinTemes** [comment]
Me sumo a la consulta. Estoy teniendo exactamente el mismo problema al queres testear una api de cobros. Hice la prueba generando varios usuarios de prueba pero siempre surge este mismo error al querer confirmar el pago

**Comment by guillote22** [comment]
El problema es más generalizado aún.
He intentado en modo producción con dos usuarios de prueba y me da el mismo error. Por último, intenté con mis datos reales, luego de haber comenzado los 30 días de prueba como vendedor, o sea pasando mi cuenta a vendedor, y no logro realizar una compra real con otro usuario anónimo. Me sigue apareciendo el mismo error.
Hasta el checkout funciona todo bien, aparece el monto, la opción para volver a la página del comercio totalmente funcional, pero cuando presiono en "confirmar pago" me aparece el mensaje "Tuvimos un problema, intenta nuevamente". EN PRODUCCIÓN CON USUARIOS REALES.
Cualquier respuesta será bienvenida. Gracias!

**Comment by guillote22** [comment]
Al parecer el problema se debía a un token que estaba agregando a la "notification_url".   Si lo agrego como parámetro o como query string, la API deja de funcionar...
