### ISSUE TITLE
notificaciones ipn - params(topic/type - id/data.id)

### ISSUE THREAD

**Issue by IsaacMiguel** [mercadopago/dx-nodejs#80]
Hola, les escribo consultando por el problema que estoy teniendo de que mas alla de funcionarme todo bien, tengo problemas en el backend de que mercadopago pega a ipn con distintos parametros.
Mi duda es si es porque pega con distintos parametros al tener distintos sdks en funcionamiento, o porque corresponden a distintas busquedas y debo agregar otros comportamientos...

mi idea seria un
const type = params.type || params.topic;
const id     = params.id || params.data.id;

**Comment by joelibaceta** [comment]
Te dejo el mail de soporte para desarrolladores, developers@mercadopago.com
Y respondo brevemente tu consulta, esta diferencia en las notificaciones corresponden a dos entidades distintas: 
- topic/type = Notificaciones IPN
- id/data.id = Webhooks
