### ISSUE TITLE
Error en búsqueda de customer

### ISSUE THREAD

**Issue by edmon1024** [mercadopago/dx-nodejs#81]
Que tal, tengo unos problemas que me sucedieron al realizar una búsqueda de un customer, al buscar un usuario por email, me devuelve una lista de usuarios, pero sin el filtro que estoy buscando, estuve revisando la wiki que tienen para poder buscar por alguna propiedad, la consulta la hago de la siguiente manera: 

    mercadopago.configure({ access_token: config.access_token })
    const configurations = { qs: { "email": "email@example.com" } }

    mercadopago.customers.search(configurations)
      .then((customer) => {
        res.status(200).json(customer);
      })
      .catch((error) => {
        res.status(500).json(error);
      });

Por otro lado, aunque me devuelve en una primer consulta una lista de usuarios, si vuelvo a intentar la consulta me manda un error, no se si se algún tipo de bloqueo por seguridad, por algún ataque de DDoS o similar, o sea algo más. Lo extraño es que no realizo muchas peticiones, solo dos consecutivas en un lapso de 5 minutos, espero me puedan orientar, el error es el siguiente:

`{ 
  "name": "MercadoPagoError",
  "message": "Unknown Error",
  "cause": "Unknown Cause",
  "status": 304
}`

Todo esto me sucede en esta versión, la 1.0.10, con el SDK anterior la 0.5.0 no me sucede ningún error y los filtros son correctos, por ejemplo al buscar de la siguiente manera:

    const mpCustom = new MP (config.access_token);
    const configurations = { "email": "email@example.com" }
    const customer = mpCustom.get("/v1/customers/search", configurations);

    customer
      .then((customer) => {
        res.status(200).json(customer);
      })
      .catch((error) => {
        res.status(500).json(error);
      });

Nota: No se si esto me podría llegar a suceder al crear un pago, o algo más, no revise más a fondo con otros módulos, porque inicialmente antes de crear un pago busco/creo un usuario

**Comment by arielfr** [comment]
@edmon1024 Gracias por el feedback. Faltaba una propiedad en el `/v1/customers/search`. Ya esta agregada. Podes descargar la versión mercadopago@1.0.11 y debería estar funcionando bien, ya que no estaba haciendo el search correctamente.

Espero tu feedback. Saludos!

**Comment by joelibaceta** [comment]
Fixed 0b69bf98022322331fdd9faf8d5d465f3c5bd1ad
