### ISSUE TITLE
Crear suscripcion - credenciales

### ISSUE THREAD

**Issue by IsaacMiguel** [mercadopago/dx-nodejs#82]
Hola, les queria consultar por el tema de que quiero crear una suscripcion y tengo problemas con las credenciales.
He probado con todas las opciones posibles, usuarios de test (entre ellos) y usuarios normales.

Este es el codigo con el que estuve probando:
(no puedo tener el post del customer, me da error de 'Unhandled rejection MercadoPagoError: access denied')

Aunque estoy usando metodos de anteriores versiones, tengo entendido deberia funcionar igual.

mercadopago v-1.0.10

```javascript
'use strict'

const mp = require('mercadopago');

mp.configure({
	client_id     : "",
	client_secret : ""
});

const _createSuscription = (customer) => {
  const preapprovalPayment = {
    reason             : 'mi item',
    payer_email        : results[0].email,
    back_url           : 'https://algunaurl.com',
    external_reference : "id del usuario a trackear",
    auto_recurring : {
      frequency          : 1,
      frequency_type     : 'months',
      transaction_amount : 100,
      currency_id        : 'ARS'
    }
  };

  mp
    .preapproval
    .create(preapprovalPayment)
    .then((susc) => {
      console.log(JSON.stringify(susc, null, 2))
    })
    .catch((error) => {
      console.log(error)
    });
};

const email = "test_user_83643741@testuser.com";

const saved_customer = mp.get("/v1/customers/search", { email: email });

saved_customer
  .then((customer) => {
    console.log(JSON.stringify(customer.response, null, 2))
  	const createCustomer = mp.post ("/v1/customers", { email: email });

  	if(customerData.results) {
    	_createSuscription(customerData.response);
    } else {
    	createCustomer
			  .then((customerData) => {
			    console.log(JSON.stringify(customerData.response, null, 2))
			  })
			  .catch((error) => {
			    console.log(JSON.stringify(error, null, 2))
			  })	
    }    
  })
  .catch(error => {
    console.log(JSON.stringify(error))
  })
```
Si me pudieran ayudar con esto seria genial.
Estoy intentando crear un boton de un solo pago, y otro boton de suscripcion. Todo en la misma pantalla.
Pero no he podido crear el de suscripcion...

Saludos.

**Comment by arielfr** [comment]
@IsaacMiguel El código es retro-compatible con la integración previa. Encontré varios errores en el código.

1.) Si estas creando usuarios de prueba, el mail tiene que cumplir con el siguiente formato **test_payer_[0-9]{1,10}**. Fijate que escribiste **test_USER**.

2.) Cuando realizas la promesa de **saved_customer** en el **then**, estas haciendo **customerData** que no esta definido dentro del código que subiste. El if debería ser `if (customer.response.results.length > 0) {`, eso esta haciendo que vaya al catch.

Te pego el código funcionando:

```javascript
mp.configure({
  access_token: '-----',
});


const _createSuscription = (customer) => {
  const preapprovalPayment = {
    reason: 'mi item',
    payer_email: results[0].email,
    back_url: 'https://algunaurl.com',
    external_reference: 'id del usuario a trackear',
    auto_recurring: {
      frequency: 1,
      frequency_type: 'months',
      transaction_amount: 100,
      currency_id: 'ARS'
    }
  };

  mp
    .preapproval
    .create(preapprovalPayment)
    .then((susc) => {
      console.log(JSON.stringify(susc, null, 2));
    })
    .catch((error) => {
      console.log(error);
    });
};

const email = 'test_payer_8364375@testuser.com';

const saved_customer = mp.get('/v1/customers/search', {
  email: email
});

saved_customer.then((customer) => {
  console.log(JSON.stringify(customer.response, null, 2));

  const createCustomer = mp.post('/v1/customers', { email: email });

  if (customer.response.results.length > 0) {
    _createSuscription(customer.response);
  } else {
    createCustomer.then((customerData) => {
      console.log(JSON.stringify(customerData.response, null, 2));
    }).catch((error) => {
      console.log('error1');
      console.log(JSON.stringify(error, null, 2));
    });
  }
}).catch(error => {
  console.log('error2');
  console.log(JSON.stringify(error));
});
```

Saludos

**Comment by arielfr** [comment]
@IsaacMiguel Agregue como punto 1.) el usar access_token en lugar de client_id y client_secret. Eso esta devolviendote el error de las credenciales

Saludos

**Comment by IsaacMiguel** [comment]
Muchas gracias @arielfr !
Perdon no contestara, pero hice toda directamente con requests a la api y no tuve ningun problema y lo pude hacer todo rapido.

Claramente fue un tema mio que no entendi como trabajar con el sdk.

Lo del email del usuario es como me lo devolvio la api de mercadopago al crear usuarios de prueba. No sabia que tenia que tener payer en vez de user.

Mil gracias de todas formas.
Saludos!

**Comment by arielfr** [comment]
@IsaacMiguel no hay problema! Saludos
