### ISSUE TITLE
Error en IPN

### ISSUE THREAD

**Issue by Albhaku** [mercadopago/dx-nodejs#83]
Que tal. Tengo un error que no me ha dejado hacer nada.
Resulta que cuándo un usuario hace un pago, espero a que MP me devuelva el ID del pago en el query y así lo asigno a una orden. Claro que eso es después de los 5 segundos que toma la redirección que hace MP a mi sitio nuevamente. MP hace un POST, notificación de pago, a mi server con un paymentId pero antes de esos 5 segundos, por lo cuál no puedo buscar una orden que lo tenga (Para validar que ese PaymentID es de alguna de mis ordenes), pero el ID de mercado pago si es válido, el IPN.manage si me da una respuesta y tal. Entonces no pasa nada, IPN sigue enviando notificiaciones, puedo esperar a las demás notificaciones.
El problema es que después de la primera, todas las demás me dan error. La 2da, 3ra y 4ta. Ya por ahí de la 5ta. notificación (del mismo pago) no pasa nada, ni error ni success (Lo sé por que hago un console.log)

El error que me da es el siguiente:
```
{ MercadoPagoError: Unknown Error
    at Object.callback (/home/ec2-user/dCastro/node_modules/mercadopago/lib/request-manager.js:318:19)
    at Request._callback (/home/ec2-user/dCastro/node_modules/request-etag/lib/request-etag.js:72:18)
    at Request.self.callback (/home/ec2-user/dCastro/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ec2-user/dCastro/node_modules/request/request.js:1081:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ec2-user/dCastro/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MercadoPagoError',
  message: 'Unknown Error',
  cause: 'Unknown Cause',
  status: 304,
  idempotency: undefined }

Unhandled rejection MercadoPagoError: Unknown Error
    at Object.callback (/home/ec2-user/dCastro/node_modules/mercadopago/lib/request-manager.js:318:19)
    at Request._callback (/home/ec2-user/dCastro/node_modules/request-etag/lib/request-etag.js:72:18)
    at Request.self.callback (/home/ec2-user/dCastro/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ec2-user/dCastro/node_modules/request/request.js:1081:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ec2-user/dCastro/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```
Mi código es el siguiente:

```
mercadopago.ipn.manage(req).then(function(response) {
		console.log('Payment found', req.query['id']);
		console.log(response);
		Order.findOne({mercadoPagoId: req.query['id']})
		.exec(function(err, order) {
			console.log('Error', err, 'Orden', order);
		// 	if (err) console.log(err);
		// 	if (!order) console.log('No se ha encontrado niguna orden');
		// 	if (order) {
		// 		console.log('Orden encontrada');
		// 		// if (response.body.collection.transaction_amount == order.total && response.body.collection.total_paid_amount == order.total) {
		// 		// 	order.paid = true;
		// 		// 	order.save(function(err, order) {
		// 		// 		if (err || !order) console.log(err, 'Hubo un error, la notificación se enviará de nuevo');
		// 		// 		if (order) res.status(200).send('Ok');
		// 		// 	});
		// 		// }
		})
	}).catch(function(error) {
		console.log(error);
	});
```

La primera vez no encuentra orden porque aún no he asignado yo el ID a mi orden, pero si encuentra el pago. A partir de la segunda, solo me da el error y ya no puedo hacer más.
Les agradecería la ayuda.

**Comment by kevinr89** [comment]
Me sucede el mismo error con otras consultas. Estoy buscando un customer por email. Hago una prueba simulando que no tiene fondos, la búsqueda por email del customer pasa correctamente y devuelve que no tiene fondos, luego al cambiar los datos en la vista del cliente y hacer una consulta nuevamente cuando busco el customer nuevamente por email me tira el error. Y es raro que si reinicio mi servidor y vuelvo a enviar la misma consulta no falla. Mi código es el siguiente:

 mercadopago.customers.search({}, { qs: { email: req.body.datos.email } }, function(err, client) {
   //VEO SI CLIENT YA EXISTE Y ACA ERR TIRA EL ERROR DE ABAJO AL HACER UNA SEGUNDA CONSULTA
 });

{ MercadoPagoError: Unknown Error
    at Object.callback (C:\Users\Kevin\nodejs\front-eldia\node_modules\mercadopago\lib\request-manager.js:318:19)
    at Request._callback (C:\Users\Kevin\nodejs\front-eldia\node_modules\request-etag\lib\request-etag.js:72:18)
    at Request.self.callback (C:\Users\Kevin\nodejs\front-eldia\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Kevin\nodejs\front-eldia\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Kevin\nodejs\front-eldia\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MercadoPagoError',
  message: 'Unknown Error',
  cause: 'Unknown Cause',
  status: 304,
  idempotency: undefined }

También me pasa un error igual con mercadopago.customers.cards.all. Gracias!

**Comment by kevinr89** [comment]
Por si es de ayuda, siguiendo el código parece que el problema es en lib/request-manager.js. En requestManager.describe = function (options) en el primer llamado modifica el options que reciben los siguientes llamados.
Con esta modificación parece funcionar bien:
```
requestManager.describe = function (opt) {
  // This method will have the context of the class that is calling this (Will have the context of the class)
  return function () {
    var options = JSON.parse(JSON.stringify(opt));
    var calledArgs = arguments;

    return new Promise(function (resolve, reject) {
      var callback = calledArgs[calledArgs.length - 1]; // Last argument will always be the callback
      var pathParameters = requestManager.getPathParamsKeyNames(options.path);
      var missingPayloadProperties = []; // Stores the missing payload path params (if there is any). POST, PUT, PATCH
      var schema = this.schema; // Schema from resource
      var needIdempotency = !!this.idempotency; // Idempotency from resource
      var config = {};
      var payload = {};
      var error;
      var totalFunctionParams;
      var haveConfig = false;

      // If callback doesn't exists add it to the arguments (Prevent code to fail)
      if (typeof callback !== 'function' || callback === undefined) {
        // Arguments is not a pure array. You need to make a normal array out of it. If not arguments.length won't work
        calledArgs = Array.prototype.slice.call(calledArgs);
        calledArgs.push(callback = function () {});
      }

      // If it is GET or DELETE the path variables needs to come from arguments
      if (options.method === 'GET' || options.method === 'DELETE') {
        haveConfig = (typeof calledArgs[calledArgs.length - 2] === 'object');
        totalFunctionParams = (haveConfig) ? (pathParameters.length + 2) : (pathParameters.length + 1);

        // Set the configurations
        if (haveConfig) config = calledArgs[calledArgs.length - 2];

        // Verify arguments quantity (invalid function call)
        if (totalFunctionParams > calledArgs.length) {
          error = new Error('Expecting parameters: ' + pathParameters.join(', ').replace(/:/g, ''));
          reject(error);
          return callback.apply(null, [error, null]);
        }

        // Replace the path parameters for the variables from the args(same Index that the one declarated on the path)
        pathParameters.forEach(function (param, index) {
          options.path = options.path.replace(param, calledArgs[index]);
        });
      } else {
        haveConfig = (calledArgs.length > 2);

        // If configurations are sent, set configurations and payload depending on the correspondent argument index
        if (haveConfig) {
          if (typeof calledArgs[calledArgs.length - 2] === 'object') config = calledArgs[calledArgs.length - 2];
          if (typeof calledArgs[calledArgs.length - 3] === 'object') payload = calledArgs[calledArgs.length - 3];
        } else if (typeof calledArgs[calledArgs.length - 2] === 'object') {
          payload = calledArgs[calledArgs.length - 2];
        }

        // Replace the path parameters from the ones on the payload
        pathParameters.forEach(function (param) {
          var propertyFromPayload = param.replace(':', '');

          if (payload && payload[propertyFromPayload]) {
            options.path = options.path.replace(param, payload[propertyFromPayload]);
            // Remove it from the payload or MercadoPago API will return an error for invalid parameter
            delete payload[propertyFromPayload];
          } else {
            missingPayloadProperties.push(propertyFromPayload);
          }
        });

        // If there are any missing properties show an error (invalid function call)
        if (missingPayloadProperties.length > 0) {
          error = new Error('The JSON is missing the following properties: ' + missingPayloadProperties.join(', '));
          reject(error);
          return callback.apply(null, [error, null]);
        }
      }

      // If the path requires /sandbox prefix on sandbox mode, prepend it
      if (options.path_sandbox_prefix !== undefined && options.path_sandbox_prefix && configurations.sandbox) {
        options.path = '/sandbox' + options.path;
      }

      // Generate the AccessToken first (required to work with MercadoPago API)
      return requestManager.generateAccessToken().then(function () {
        return requestManager.exec({
          schema: schema,
          base_url: (options.base_url !== undefined) ? options.base_url : '', // Overrides the base URI
          path: options.path,
          method: options.method,
          config: config, // Configurations object
          payload: payload, // Payload to send
          idempotency: needIdempotency // Needs the idempotency header
        });
      }).then(function (response) {
        resolve(response);
        return callback.apply(null, [null, response]);
      }).catch(function (err) {
        reject(err);
        return callback.apply(null, [err, null]);
      });
    }.bind(this));
  };
};
```

**Comment by arielfr** [comment]
@kevinr89 Hola, podrás comentarme especificamente que fue lo que cambiaste, así realizo la prueba y en caso de necesitar modificación la hago. Estas haciendo un payment?

@Albhaku vi que estas haciendo un `req.query['id']` y pones en el `console.log` como si fuera un payment id. Te comento que el IPN no devuelve payments ids, ni merchant_orders id, etc...
El IPN retorna un **notification**. Ese notification tiene un Id y un Topico. El `ipn.manage` lo que hace internamente es fijarte el topico y realizarte la segunda llamada a la API de manera automática, si es un Payment, le pega a /notifications y te consigue el payment, si es un Merchant Orders, le pega a merchant orders, y así sucesivamente dependiendo del topico. Es por eso que quiero entender bien cual fue el caso. Podrías detallarme los steps.

Muchas Gracias!

**Comment by arielfr** [comment]
@kevinr89 @Albhaku Ya realizamos el Debug necesario y encontramos el error. Al realizar una segunda llamada inmediatamente después de la primera el status code de la respuesta pasa a ser 304. Este statusCode no esta mapeado como valido dentro de la SDK. Ya hicimos la corrección y publicamos el fix en el paquete de mercadopago@1.0.12.

Por favor, actualicen la dependencia y realicen sus pruebas.

Muchas Gracias
