### ISSUE TITLE
Generar card_tokens

### ISSUE THREAD

**Issue by kevinr89** [mercadopago/dx-nodejs#84]
Hola! Existe algún método para llamar a "/v1/card_tokens"? Ya que necesito generar un token para una tarjeta guardada y no encuentro la llamada a esa ruta. Gracias!

**Comment by joelibaceta** [comment]
Hola @kevinr89 no recomendamos realizar llamadas al API de CardTokens desde el backend ya que esto debe realizarse solo en los servidores de MercadoPago (Sin pasar por tu servidor), para ello usar la SDK de Javascript para FrontEnd.
