### ISSUE TITLE
Problema para visualizar métodos de pago con el SDK para generar pago

### ISSUE THREAD

**Issue by edmon1024** [mercadopago/dx-nodejs#85]
Que tal, espero me puedan ayudar con el siguiente problema que tengo.

De que forma en javascript (reactjs) podría llamar a la función de mp.getPaymentMethods()

SI logro visualizar el arreglo de métodos de pago, pero en algunos casos no se si sea por algún retardo no llego a poder recibir los métodos de pago, retorno el arreglo vacío []

Intente llamarlo la función cuando carga mi componente, o cuando se renderiza, pero de manera aleatoria no los logro visualizar.

Se podrá utilizar una promesa o un callback para poder obtener los datos para poder mostrarlos al usuario? esto del lado del cliente con la public_key

**Comment by arielfr** [comment]
@edmon1024 Podrías mostrarme el código?

**Comment by edmon1024** [comment]
Primero al cargar el componente, cambio la public_key, valido que se haya cargado el sdk en el cliente y poder setear el campo:

 ```
 componentDidMount(){
    if(Mercadopago){
      Mercadopago.setPublishableKey(config.public_key)
    }
  }
```

Después en el render mando llamar los métodos de pagos para poder mostrarlos al usuario busco un método en particular por su ID, y lo muestro, pero lo que les mencionaba, por momentos no muestra algún dato, el ejemplo es el siguiente:

```
render() {
    const paymentMethods = Mercadopago.getPaymentMethods()
    const oxxo = paymentMethods.find(x => x.id == 'oxxo')
   return(
     { oxxo ? 
        <span>oxxo.name</span>
     :null}       
   )
}
```


Estaba probando de otra manera, buscando directamente cada método de pago por el id, pero aun así llego a tener problemas al mostrarlos:

```
  componentDidMount(){
    if(Mercadopago){
      Mercadopago.setPublishableKey(config.public_key)

      const ticket = { 'payment_method_id': 'oxxo' }

      const mTicket = { "payment_method_id": 'oxxo' }
      Mercadopago.getPaymentMethod(mTicket, this.getTicket )
    }
  }
```
  ```
getTicket(status, result){
    if(status === 200 && result.length > 0 && result[0].status == 'active'){
      this.setState({ oxxo: result[0] })
    }
  }
```

Cualquier comentario seria excelente, por si algo estoy me falta por hacer.

**Comment by arielfr** [comment]
@edmon1024 El problema no recide en la SDK. Tiene que ver con el ciclo de vida de React. En tu ejemplo:

```javascript
render() {
    const paymentMethods = Mercadopago.getPaymentMethods()
    const oxxo = paymentMethods.find(x => x.id == 'oxxo')
   return(
     { oxxo ? 
        <span>oxxo.name</span>
     :null}       
   )
}
```

Deberías tener un state, los render de react cambian de acuerdo al state. Deberías tener un state inicial con un loading = true, luego hacer el AJAX (SDK mercadopago) y cuando la promesa se resuelva tenes que actualizar el state con la respuestas y cambiar el loading = false. Así el render se hace de nuevo y ahora la respuesta que pusiste en alguna variable del state se renderiza. Podes usar el loading para mostrar un spinner si queres.
