### ISSUE TITLE
Calcular shipping

### ISSUE THREAD

**Issue by AgustinQuetto** [mercadopago/dx-nodejs#86]
Hola, que tal.
¿Alguno logró calcular el shipping? No encuentro método en la wiki y añadiendo al json donde hace post el zip no lo calcula en el pago.

Gracias.

**Comment by KevinTemes** [comment]
Me sumo a la consulta. Ya hace varios días que estoy leyendo sobre este tema y no encuentro en la documentación ningún lugar donde se explique de forma concreta cómo hacer esto.

**Comment by yairvillarp** [comment]
Gente, estube en contacto con la gente de MP y esta sdk NO tiene shipping por el momento, asique tenemos que esperar a que lo tengan listo.

**Comment by josantana** [comment]
There is any chance of providing a method to estimate shipping costs and delivery time using _Mercado Envios_? It has past months since the last comment on this thread. This issue should not be closed as it was not resolved.
