### ISSUE TITLE
Money request payer_email Error

### ISSUE THREAD

**Issue by scarmarco** [mercadopago/dx-nodejs#92]
Hello, I'm trying to use money request API but getting an error with `payer_email` prop.

*code*:
![image](https://user-images.githubusercontent.com/8265737/39884782-58e5d218-5461-11e8-88c4-0076f4128cca.png)

*error*:
![image](https://user-images.githubusercontent.com/8265737/39884797-65bc8c8e-5461-11e8-9da2-89c4d90e47d8.png)

**Comment by arielfr** [comment]
Hi @scarmarco, this was a bug of the SDK. That's not the respond from the API is the schema validator implemented on the NodeJS SDK.

This is fix here https://github.com/mercadopago/dx-nodejs/pull/94. Please update your mercadopago NPM dependency to the latests version. It is `1.0.15` (just updated)

Thanks for taking the time to post the issue

Cheers,
