### ISSUE TITLE
MercadoPagoError: Unknown Error

### ISSUE THREAD

**Issue by MatiDeve** [mercadopago/dx-nodejs#97]
https://ibb.co/k1XHfy

Hola buenas tardes, estuve revisando la lista de problemas y que se solucionaba actualizando a la version 1.0.12 (actualmente seria la 1.0.15 que es la que tengo), pero aun asi no me funciono.

Los introduzco mas en contexto: 
El usuario de compra y el de venta son de pruebas, y uso tarjetas de pruebas. Uso solamente merchant_orders. Tengo la url registrada con merchant_orders y payments

1) Paso al usuario el link para pagar 
2) Entro con el usuario de compra al link, completo los datos y me dice que en maximo 24hs se efectua el pago
3) Instantaneamente recibo tres consultas:
a) Merchant_order con id "X". Me parece que es para registrar la compra
b) Misma data que el primero, pero ahora en el response aparece el dinero pagado
c) Payment, id "Y". Unknown error: unknown cause

La primer notificacion sería para crear la compra y la segunda confirma el pago? Y la tercera? Porque recibo un payment que ademas me causa error?

Saludos, espero respuesta!

**Comment by arielfr** [comment]
Buenas @MatiDeve podrías comentarme como estas haciendo la prueba. Estas haciendo o simulando la compra con usuarios de prueba?

**Comment by arielfr** [comment]
@MatiDeve de casualidad estas usando modo sandbox?

**Comment by arielfr** [comment]
@MatiDeve publique una nueva versión. Podrías probar. En caso de falla podrías compartirme el código del endpoint?

**Comment by MatiDeve** [comment]
Hola, muchas gracias por tu respuesta y la nueva version. Anduvo perfectamente. Aun asi necesitas el código anterior (uso usuarios de prueba) o lo cerramos aca? Nuevamente muchas gracias

**Comment by arielfr** [comment]
No, no hace falta 👍 Mil gracias
